-- MySQL Script generated by MySQL Workbench
-- Wed Oct 10 20:33:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT(9) NOT NULL,
  `pst_phone` BIGINT NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT UNSIGNED NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(6,2) UNSIGNED NOT NULL,
  `cus_total_sales` DECIMAL(6,2) UNSIGNED NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pet_price` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pet_age` TINYINT UNSIGNED NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_petstore_idx` (`pst_id` ASC) VISIBLE,
  INDEX `fk_pet_customer1_idx` (`cus_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_petstore`
    FOREIGN KEY (`pst_id`)
    REFERENCES `mydb`.`petstore` (`pst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_customer1`
    FOREIGN KEY (`cus_id`)
    REFERENCES `mydb`.`customer` (`cus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Bryar', '6691 Dui St.', 'Charlottetown', 'PE', 94665, 3655741387, 'mollis@ipsumprimisin.org', 'Aliquam Ornare Corporation', 'sodales');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Joshua', 'Ap #527-8787 Mauris. St', 'Bulnes', 'FL', 1604, 1505379862, 'eu@turpisAliquam.org', 'Nec Corp.', 'ornare,');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Wade', '1717 A Avenue', 'Minturno', 'NY', 2593, 3154957944, 'a@etrutrumnon.org', 'Urna Vivamus Corporation', 'Aenean');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Janna', '173-392 Iaculis Avenue', 'Buckie', 'AB', 405, 2344542716, 'Cras.dolor.dolor@Sedcongueelit.co.uk', 'Iaculis Odio Nam Consulting', 'Lorem');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Arden', '366-802 Tellus Road', 'Feilding', 'NI', 15245, 2904016767, 'nibh.lacinia.orci@Nunclectus.com', 'In Cursus Et Limited', 'arcu.');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Tana', 'P.O. Box 168, 6920 Mauris', 'Aulnay-sous-Bois', 'IL', 12345, 5743128177, 'augue.porttitor@Sedet.net', 'Arcu Morbi Sit Limited', 'Quisque');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Imogene', '1532 Et Avenue', 'Redlands', 'QL', 40410, 6787635161, 'eu@nectempus.edu', 'Ornare Facilisis Eget Foundation', 'at');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Brody', '661-1431 Quisque St.', 'San José de Maipo', 'MS', 69925, 7425127069, 'feugiat.metus.sit@vitae.ca', 'A Enim Inc.', 'est');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Elmo', '6837 Enim. Rd.', 'Kansas City', 'MS', 77785, 2562262064, 'id@duiaugue.co.uk', 'Nascetur Ridiculus LLP', 'sem.');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_notes`) VALUES (DEFAULT, 'Stacey', 'P.O. Box 871, 6061 Mi St.', 'Le Mans', 'PA', 87008, 8531748432, 'a.tortor@purusDuiselementum.edu', 'Ullamcorper LLP', 'elit.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Ralph', 'MacKenzie', '114 Aptent Av.', 'Alcobendas', 'MA', 9499, 7637741218, 'pede@Lorem.edu', 48.52, 15.76, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Hilary', 'Prescott', '870 Cras Rd.', 'Sosnowiec', 'SL', 4471, 7462786180, 'mus.Donec@malesuada.co.uk', 48.81, 96.62, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Tanner', 'Charissa', '411-3348 Sit Ave', 'Bergama', 'Fl', 66629, 9422727801, 'dolor@Suspendissenonleo.net', 51.29, 36.39, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Rama', 'Kato', '917-6099 Tellus Ave', 'Quinte West', 'OT', 30471, 6687741248, 'blandit@ultricesmaurisipsum.edu', 59.68, 20.44, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Nasim', 'Carson', '2718 Quisque St.', 'Oklahoma City', 'OK', 1929, 3193035249, 'est.congue.a@auctorquis.ca', 91.45, 30.9, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Shannon', 'May', 'Ap #525-2613 Purus. Road', 'İskenderun', 'HT', 54842, 4987983485, 'enim.sit.amet@elitsedconsequat.com', 33.23, 11.32, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Merritt', 'Lillian', '489-1836 Cras Street', 'Nässjö', 'FL', 14185, 5786793943, 'turpis@maurissitamet.net', 22.3, 38.24, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Galena', 'Tasha', '885-2656 Et, St.', 'Enns', 'FL', 16599, 3895956575, 'non.lorem@feugiat.edu', 94.55, 85.26, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Lyle', 'Zeus', '2750 In Ave', 'Newcastle', 'NS', 60621, 7137507412, 'consectetuer.rhoncus.Nullam@vestibulumneceuismod.edu', 10.21, 66.18, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Janna', 'Kamal', 'Ap #602-4364 Volutpat. Street', 'Gdynia', 'PM', 79143, 9897885501, 'eu@semmagnanec.edu', 34.8, 93.78, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 1, 'Irish Wolfhound', 'm', 2000.00, 1500.00, 1, 'brown', NULL, 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 2, 'Saluki', 'm', 2500.00, 2500.00, 1, 'brown', NULL, 'n', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 3, 'Pharaoh Hound', 'f', 2500.00, 6500.00, 1, 'gold', NULL, 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 4, 'Akita', 'f', 1500.00, 4500.00, 1, 'white and gold', NULL, 'n', 'n', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 5, 'Tibetan Mastiff', 'm', 2200.00, 7000.00, 1, 'gold', NULL, 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 6, 'Rottweiler', 'f', 2000.00, 8000.00, 1, 'black', NULL, 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 7, 'Lowchen', 'f', 5000.00, 8000.00, 1, 'grey', NULL, 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, 8, 'Chow Chow', 'm', 3000.00, 8500.00, 1, 'gold', NULL, 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 9, 'English Bulldog', 'f', 2500.00, 9000.00, 1, 'white and brown', NULL, 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, 10, 'Samoyed', 'f', 4000.00, 11000.00, 1, 'white', NULL, 'y', 'y', NULL);

COMMIT;

